# Generated by Django 4.1 on 2022-12-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PillsInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndc11', models.CharField(max_length=200)),
                ('rxcui', models.IntegerField(default=0)),
                ('pill_name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(max_length=200)),
            ],
        ),
    ]
