# Generated by Django 4.1 on 2022-12-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillrecognition', '0003_alter_uploadimage_pill_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='pill_image',
            field=models.ImageField(blank=True, default='uploaded_pill/default.png', max_length=255, null=True, upload_to='uploaded_pill'),
        ),
    ]
