# Generated by Django 4.1 on 2022-12-07 22:12

from django.db import migrations, models
import pillrecognition.storage


class Migration(migrations.Migration):

    dependencies = [
        ('pillrecognition', '0004_alter_uploadimage_pill_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='pill_image',
            field=models.ImageField(blank=True, default='uploaded_pill/default.png', max_length=255, null=True, storage=pillrecognition.storage.OverwriteStorage(), upload_to='uploaded_pill'),
        ),
    ]
