# Generated by Django 4.1 on 2022-08-06 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_remove_contactor_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactor",
            name="time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date published"
            ),
            preserve_default=False,
        ),
    ]
