# Generated by Django 4.1 on 2022-08-06 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_contactor_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactor",
            name="time",
        ),
    ]
