# Generated by Django 4.1 on 2022-08-06 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_remove_contactor_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactor",
            name="pub_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date published"
            ),
            preserve_default=False,
        ),
    ]
