# Generated by Django 4.1 on 2022-08-06 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_contactor_pub_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactor",
            name="pub_date",
        ),
        migrations.AddField(
            model_name="contactor",
            name="received_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
